#
# Required top level configuration
#
name = "sanity-studio-dev"
type = "webpack"
workers_dev = false
account_id = "9a528f69de44167d6e10333ab59f7b23"
zone_id = "13fbfe41e9a2d508147ff299afa9de7c"
webpack_config = "./workers/webpack.config.js"

#
# Environment Defaults (for development & pre-staging worker testing)
#
# -- inherited for all environments unless overridden!
#
route = "studio-dev.sboc.us/*"

[vars]
DEBUG = "true"
ENV_NAME = "devworker"

[site]
bucket = "studio/dist"
entry-point = "workers"
exclude = ["**/*.map"]

#
# Staging env overrides
#
[env.staging]
name = "sanity-studio-staging"
route = "studio-staging.sboc.us/*"
[env.staging.vars]
DEBUG = "true"
ENV_NAME = "staging"

#
# Production env overrides
#
[env.production]
name = "sanity-studio-production"
route = "studio.sboc.us/*"
[env.production.vars]
DEBUG = "false"
ENV_NAME = "prod"
